Pernyataan Kondisional, kalo mau dipakein string kaya x+a gitu, a nya perlu pake "a" biar ga error

```
# This is formatted as code
```



In [ ]:
x = eval(input("Masukan sebuah bilangan: "))
if x>0:
  print("Bilangan Positif")
elif x<0:
  print("Bilangan Negatif")
elif x==0:
  print("0")

Masukan sebuah bilangan: 8
Bilangan Positif


LOOPING
ada while, ada for loop,

kalo range nanti araynya akan selalu dari nol.

In [ ]:
for i in range (4):
  print(i)
print("For Loop Example 2")
for i in range (0,5):
  print (i)
print("Contoh For Loop 3")
for i in range (0,8,3):
  print (i)
print("Contoh For Loop 4")
for i in range (9,1,-1):
  print (i)
print ("Contoh 5")
for i

0
1
2
3
For Loop Example 2
0
1
2
3
4
Contoh For Loop 3
0
3
6
Contoh For Loop 4
9
8
7
6
5
4
3
2
Contoh 5


In [ ]:
i=0
while i <= 5:
  print(i+7)
  i +=1
print ("Done")

7
8
9
10
11
12
Done


Error Handling

In [ ]:
1/0

ZeroDivisionError: ignored

In [ ]:
try:
  x=eval(input("Integer tak nol: "))
  print(1/x)
except:
  print("Xnya masih nol")

#nanti digunain buat metnum di bisception method

Integer tak nol: 0
Xnya masih nol


In [ ]:
"2" + 2

TypeError: ignored

Modul nanti berguna buat beberapa metode
1. modul nummpy
2. modul nebulet

fungsinya dia menginstall perintah agar fungsi di phyton bisa digunakan

In [ ]:
import numpy as np

In [ ]:
A=np.array([True,4,7.5,"Jean"])
B=np.array([5,6.2])
C=np.array([1,2,3,4])

In [ ]:
P=np.array([[1,2],[5,0]])
Q=np.array([[4,7],[1,8]])
R=np.array([[1,2,20,1],[-1,0,-5,6]])
#ini bisa buat bikin matriks

In [ ]:
print(P)
print(R)

[[ 1  2]
 [-1  0]]
[[ 1  2 20  1]
 [-1  0 -5  6]]


In [ ]:
Lisst=[1,2,3,-1,3]

In [ ]:
lisst=[0]

In [ ]:
print(A)
print(A[0])
print(A[-3])
print(P)
print(P[0,1])

print(A[1:]) #manggil dari array ke 1 sampe akhir
print(P[1:])

['True' '4' '7.5' 'Jean']
True
4
[[ 1  2]
 [-1  0]]
2
['4' '7.5' 'Jean']
[[-1  0]]


In [ ]:
print("Nilai P")
print(P)
print("Nilai Q")
print(Q)
print("Jumlah Matriks")
print(P+Q)
print("Selisih Matriks")
print(P-Q)
print("Perkalian Matriks")
print(P*Q)
print("Pembagian Matriks")
print(P/Q)
print("Modulo Matriks")
print(P%Q)
print("Division")
print(P//Q)
print("Pangkat")
print(P**Q)
print("Operasi dengan nilai a")
print(P+2)

Nilai P
[[1 2]
 [5 0]]
Nilai Q
[[4 7]
 [1 8]]
Jumlah Matriks
[[5 9]
 [6 8]]
Selisih Matriks
[[-3 -5]
 [ 4 -8]]
Perkalian Matriks
[[ 4 14]
 [ 5  0]]
Pembagian Matriks
[[0.25       0.28571429]
 [5.         0.        ]]
Modulo Matriks
[[1 2]
 [0 0]]
Division
[[0 0]
 [5 0]]
Pangkat
[[  1 128]
 [  5   0]]
Operasi dengan nilai a
[[3 4]
 [7 2]]


In [ ]:
from tabulate import tabulate
#kalo tabulate gapake bintang cmn fungsi tabulate yang umum aja kalo yang pake bintang brrti semua

In [ ]:
table = [["Jeruk",2],["Nanas",2]]
Judul = ["Jenis buah","Kuantitas"]

In [ ]:
print(table)
print(tabulate(table,headers=Judul,tablefmt="pretty"))

[['Jeruk', 2], ['Nanas', 2]]
+------------+-----------+
| Jenis buah | Kuantitas |
+------------+-----------+
|   Jeruk    |     2     |
|   Nanas    |     2     |
+------------+-----------+


In [ ]:
table=[["Jeruk",2,1000],["Nanas",4,3000],["Mangga",2]]
Judul = ["Jenis buah","Kuantitas","Harga"]
print(tabulate(table,headers=Judul,tablefmt="pretty"))

+------------+-----------+-------+
| Jenis buah | Kuantitas | Harga |
+------------+-----------+-------+
|   Jeruk    |     2     | 1000  |
|   Nanas    |     4     | 3000  |
|   Mangga   |     2     |       |
+------------+-----------+-------+
