Program ini dibuat untuk membantu Luffy bertemu dengan Ace yang terkunci di Impel Down. Iya terkunci di ruangan ke "k", dari ruangan 1 sampai dengan K terdapat sebanyak "n" kode yang dapat membuat gembok. Kode tersebut merupakan kode acak yang terdiri atas angka dari 1-100. Terdapat sejumlah "n" genap kode di setiap gembok.

In [ ]:
import random
while True:
    K = int(input("Jumlah ruangan: ")) #k=jumlah ruangan
    for i in range(1,K+1): #jumlah ruangan dari 1 ke k
        Jumlah_gembok = int(input(f"Jumlah gembok ruangan ke-{i}: ")) #n=jumlah gembok
        while jumlah_gembok % 2 != 0:
            print("Salah. Input harus genap!\n") #n harus genap
            jumlah_gembok = int(input(f"Jumlah gembok ruangan ke-{i}: "))
        my_list1 = []
        my_list2 = []
        for j in range(0,jumlah_gembok):
            my_list1.append(random.randint(-100,100)) #range kode untuk a dari -100 hingga 100
            my_list1!=0
            my_list2.append(random.randint(-100,100)) #range kode untuk b dari -100 hingga 100
            my_list2!=0
        print(f"a_i: {my_list1}")    #print kode a
        print(f"b_i: {my_list2}\n")   #print kode b

a_i: [41, 12]
b_i: [-61, 76]

a_i: [-51, -65, 49, -86, -98, -46]
b_i: [11, 97, 91, -66, 81, 89]

a_i: [-87, -95, 94, 84]
b_i: [-88, 98, 65, 97]



Program ini adalah program untuk menentukan house dari masing-masing pelajar dengan ketentuan yaitu:

1. Username terdiri atas 3 digit
2. Nomor absen dimulai dari 00 sampai 99 dan diletakkan di belakang
3. Terdapat kode house (G/H/R/S) di dalam username
4. Setiap house terdiri atas 25 pelajar
5. Penentuan house dilakukan secara acak oleh The Sorting Hat dimulai dari peserta dengan nomor absen terkecil
6. Tidak ada house yang memiliki lebih dari 25 pelajar

In [3]:
import random

house = ["G","H","R","S"] #list 4 kode house username
house_array = [[],[],[],[]]
for a in range(0,100) : #terdapat 100 kuota
  for b in range (len(house)):
    if len(house_array[b-1]) == 25 : #masing-masing house terdiri atas 25 orang
        house_array.pop(b-1)
        house.pop(b-1)

  pilihan = random.randint(0, len(house)-1)

  house_array[pilihan].append(a)

  print("%s%02d" % (house[pilihan], a))

G00
G01
G02
H03
R04
G05
G06
H07
H08
G09
R10
S11
H12
R13
S14
H15
G16
S17
H18
G19
R20
H21
H22
R23
S24
R25
R26
S27
S28
R29
R30
R31
R32
R33
H34
G35
S36
S37
S38
H39
H40
S41
H42
R43
S44
S45
G46
H47
R48
H49
G50
H51
S52
H53
H54
H55
H56
R57
S58
S59
S60
S61
G62
H63
R64
G65
H66
G67
G68
G69
G70
S71
S72
H73
G74
S75
S76
S77
H78
H79
R80
R81
R82
H83
R84
R85
R86
G87
G88
R89
R90
G91
R92
S93
G94
S95
G96
G97
G98
S99


SOAL BONUS

Program ini adalah program untuk mengecek kekuatan fitur password dengan syarat yaitu:

1. Panjang 5 digit atau lebih
2. Mengandung huruf besar dan huruf kecil
3. Mengandung angka
4. Mengandung karakter khusus (~,!,@,#,$,%,^,&,*,<,>)

In [4]:
print('Masukkan password Anda dengan syarat : ')                                 #print peraturan
print('1. Memiliki panjang lebih dari sama dengan 5 karakter')
print('2. Mengandung setidaknya satu huruf kapital')
print('3. Mengandung setidaknya satu huruf kecil')
print('4. Mengandung setidaknya satu angka')
print('5. Mengandung setidaknya satu karakter')

password=input('Enter your password: ')                                         #untuk insert password

def passwordchecker(password):                                                  #membuat def
  a= "~","!","@","#","$","%","^","&","*","<",">"                                #list karakter khusus
  if len(password)>=5 and any(string.isupper() for string in password) and any(string.islower() for string in password) and any(string.isnumeric() for string in password) and any(password) in a:
    print('Password sudah kuat')                                                #peraturan harus terpenuhi semua dengan penghubung "and" akan mengoutput Password sudah kuat

  else :
    print ('Password belum kuat')                                               #apabila salah satu dari peraturan tidak terpenuhi akan mengoutpyt Password belum kuat
(passwordchecker(password))

Masukkan password Anda dengan syarat : 
1. Memiliki panjang lebih dari sama dengan 5 karakter
2. Mengandung setidaknya satu huruf kapital
3. Mengandung setidaknya satu huruf kecil
4. Mengandung setidaknya satu angka
5. Mengandung setidaknya satu karakter
Enter your password: soahd284As.
Password belum kuat


Program ini adalah program untuk mengetahui berapa banyak gunung atau lembah yang dilewati oleh Messi berdasarkan catatan dari langkah-langkah yang dibuatnya. Di dalam catatannya terdapat beberapa istilah legenda sesuai dengan gambar dari langkah-langkah catatannya.

Apabila ia melangkah turun dia akan mencatat "T"

Apabila ia melangkah naik dia akan mencatat "N"

Setiap langkah mewakili satu unit perubahan ketinggian dalam MDPL

In [5]:
def hitung_lembah(steps, path):                                                 #definisi untuk menghitung lembah

  MDPL = 0
  lembah = 0

  for steps in path :                                                                        #pengecekkan steps sesuai path

    if steps == 'T':            #saat steps turun MDPL + 1
      MDPL +=1

    if steps == 'N':            #saat steps naik MDPL +1
      MDPL -=1

      if MDPL == 0:             #lembah +1 ketika steps turun=steps naik
        lembah +=1

  print("Jumlah lembah yang dilewati =", end = "")
  return lembah

In [6]:
def hitung_gunung(steps,path):

  MDPL = 0
  gunung = 0

  for steps in path :

    if steps == 'N':      #saat steps naik MDPL + 1
      MDPL+=1

    if steps == 'T':       #saat steps turun MDPL - 1
      MDPL-=1

    if MDPL == 0:       #gunung +1 ketika steps naik=steps turun
        gunung+=1

  print("Jumlah gunung yang dilewati= ", end = "")
  return gunung

In [7]:
steps = 9
path = "NNTTNNTNT"

print(hitung_lembah(steps,path))
print(hitung_gunung(steps,path))

Jumlah lembah yang dilewati =0
Jumlah gunung yang dilewati= 1


Program ini adalah program untuk membuat fungsi "matriks_keren" dengan ketentuan

1. Fungsi tersebut menerima input array berukuran 1 × n berisi integer [k1, k2, k3, ... , n].
2. Buat sebuah matriks A yang berukuran n × n dengan ketentuan entri sebagai berikut

  a. Untuk entri ai,j pada matriks A dengan i = j (alias diagonal utama), berikan nilai 0

  b. Untuk entri ai,j pada matriks A dengan i < j (alias elemen di atas diagonal utama), berikan nilai berupa 2 × (elemen array ke i) − (elemen array ke j)
  
  c. Untuk entri ai,j pada matriks A dengan i > j (alias elemen di bawah diagonal utama), berikan nilai berupa (elemen array ke i) + 2 × (elemen array ke j)

3. Setelah mendapatkan suatu matriks A dari aturan di atas, Naruto ingin mengganti nilai pada diagonal utamanya (ai,i) dengan ketentuan sebagai berikut:
  
  a. Buat suatu submatriks dari A dengan menghilangkan semua entri baris-i dan kolom-i (seharusnya submatriks A memiliki ukuran n − 1 × n − 1 )

  b. Isi diagonal utama submatriks yang terbentuk dengan nilai 0

  c. Nilai entri ai,i dari matriks A adalah nilai maksimum dari entri submatriks yang telah terbentuk dari poin 3a dan 3b

In [1]:
import numpy  #mengimport modul numpy

def matriks_keren(w) :
    matriks_A = numpy.array([[0]*len(w) for i in range(len(w))])
    for row in range(len(w)) :
        for column in range(len(w)) :
            if row == column :
                matriks_A[row,column] = 0
            if row < column :
                matriks_A[row,column] = 2*w[row] - w[column]
            if row > column :
                matriks_A[row,column] = w[row] + 2*w[column]
    for row_A in range(len(w)) :
        for column_A in range(len(w)) :
            if row_A == column_A :
                matriks_B = matriks_A.copy()
                matriks_B = numpy.delete(matriks_B,column_A,1)
                matriks_B = numpy.delete(matriks_B,row_A,0)
                for row_B in range(len(matriks_B)) :
                    for column_B in range(len(matriks_B)) :
                        if row_B == column_B :
                            matriks_B[row_B,column_B] = 0
                matriks_A[row_A,column_A] = matriks_B.max()
    print(f"{matriks_A}")

In [2]:
matriks_keren([9,4,2,5])

[[13 14 16 13]
 [22 23  6  3]
 [20 10 23 -1]
 [23 13  9 22]]
